### PR TITLE
Initial commit of service controller.

### PR DESCRIPTION
**Pull request by bmelville**

### CODE REVIEW

**Comment by MHBauer** [comment]
let's not commit binaries. `cf/service_controller/service_controller`

`go build` in the `cf/service_controller` works for me.

**Comment by bmelville** [comment]
Yikes, totally missed that, updated in the commit.

**Comment by duglin** [comment]
can you move this to be under the "kube" dir since this will be a kube-focused impl? I was saving the 'cf' dir for the ruby/CF extracted code.

**Comment by bmelville** [comment]
Understood, please take another look.

**Comment by duglin** [comment]
LGTM

**Pull request merged**
